elasticsearch_connector.cluster.*:
  type: config_entity
  label: 'Elasticsearch Cluster'
  mapping:
    cluster_id:
      type: string
      label: 'Cluster ID'
    name:
      type: string
      label: 'Cluster Name'
    status:
      type: string
      label: 'Cluster Status'
    url:
      type: string
      label: 'Cluster URL'
    proxy:
      type: string
      label: 'Cluster Proxy'
    options:
      type: mapping
      label: 'Options'
      mapping:
        multiple_nodes_connection:
          type: boolean
          label: 'Multiple Nodes Connection'
        use_authentication:
          type: integer
          label: 'Use Authentication'
        authentication_type:
          type: string
          label: 'Authentication Type'
        username:
          type: string
          label: 'User Name'
        password:
          type: string
          label: 'Password'
        timeout:
          type: string
          label: 'Timeout'
    locked:
      type: boolean
      label: 'Locked'
